### ISSUE TITLE
自动预览在微信里打开报错

### ISSUE THREAD

**Issue by xiaojiaxi** [wechat-miniprogram/mobx-miniprogram-bindings#1]
![IMG_C597D5C19B52-1](https://user-images.githubusercontent.com/3666753/63745271-5b2fec00-c8d4-11e9-8dc0-28410bc156ba.jpeg)

**Comment by LastLeaf** [comment]
需要将 mobx-miniprogram 更新到 4.13.2 。

**Comment by LastLeaf** [comment]
已更新代码片段。

**Comment by borie88** [comment]
@LastLeaf 你们需要更新npm包。现在还是4.13.1，依然报错

**Comment by LastLeaf** [comment]
@borie88 
抱歉。之前 npm latest tag 有问题。现在将 latest 置为 4.13.2 了。
