### ISSUE TITLE
为啥要映射action?

### ISSUE THREAD

**Issue by chenzhutian** [wechat-miniprogram/mobx-miniprogram-bindings#12]
其实是一个无关紧要的问题
我在用typescript重写这个库, 然后想到为啥要映射actions, 直接用store.action的形式调用不是更好么? 可以强制区分store的action和组件本地的函数

**Comment by LastLeaf** [comment]
算是模仿别的库做的。没有特殊的用意。

**Comment by chenzhutian** [comment]
明白了, 谢谢!
