### ISSUE TITLE
store之间互相调用可以做到吗

### ISSUE THREAD

**Issue by doKill** [wechat-miniprogram/mobx-miniprogram-bindings#14]
RT.

**Comment by LastLeaf** [comment]
没太明白你指的调用是啥。

不过这个是 mobx 本身的特性，建议查询 mobx 的文档。

**Comment by doKill** [comment]
> 没太明白你指的调用是啥。
> 
> 不过这个是 mobx 本身的特性，建议查询 mobx 的文档。

比如在详情store调用列表store的action

**Comment by LastLeaf** [comment]
可以直接拿到列表 store 对象去调用里面的 action 。（这个是 mobx 支持的。）

**Comment by doKill** [comment]
> 可以直接拿到列表 store 对象去调用里面的 action 。（这个是 mobx 支持的。）
