### ISSUE TITLE
应该如何合并多个 store？

### ISSUE THREAD

**Issue by Leskur** [wechat-miniprogram/mobx-miniprogram-bindings#19]

**Comment by LastLeaf** [comment]
storeBindings 可以是一个数组。具体可以参考 [这个测试用例](https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/blob/f9494e1a15cb6cc7f2f45a0425a06d662f66ef18/test/index.test.js#L199) 。

（如果你问的是在 mobx 中的 multi store 管理方法，建议搜索 mobx 的一些示例。）

**Comment by Leskur** [comment]
谢谢，我就是看到大多人都使用 storeBindings 绑定多个 store，很少使用 multi store 管理，所以有这个疑问。

没有推荐的做法那我按自己的来😁

**Comment by LastLeaf** [comment]
这里并不关心具体的 store 管理方式。（对于 mobx 各种做法的好坏这里也不方便讨论。）

请按你的想法来。
