### ISSUE TITLE
能否把多个store分开绑定？

### ISSUE THREAD

**Issue by missannil** [wechat-miniprogram/mobx-miniprogram-bindings#20]
比如在一个页面中有 商品列表渲染组件，有购物车组件，有用户组件，每个组件都有自己的store数据，现在的情况下，只能把他们提到一个store中，在要绑定的数据越来越多的情况下，不利于代码阅读和维护。想到的解决办法如下:
1. 多个组件分别些自己的Behavior，通过页面的behaviors属性合并，可是当前情况 只有最后的Behavior中的绑定属性有效(覆盖了前面behavior中的绑定属性)
![image](https://user-images.githubusercontent.com/55321481/117754756-91023900-b24d-11eb-9848-0a9071eb6169.png)

2. 改变绑定方法如图
![image](https://user-images.githubusercontent.com/55321481/117754959-f22a0c80-b24d-11eb-84c1-f68b7773b1b8.png)

不知道是否合理，总之是想实现多sotre分开写，以达到阅读和维护方便，现在把所有sotre都写在一个里面，多的时候真的头疼，还要去找这个store是属于哪个组件的。这个action是属于哪个组件的。就好比把各个Behavior中的computed合并一样。

**Comment by LastLeaf** [comment]
考虑对第一种方式提供支持。

**Comment by missannil** [comment]
自己尝试写了一下，还不错，暂时先用

**Comment by dhlolo** [comment]
[官方推荐的方式](https://www.mobxjs.com/defining-data-stores#%E7%BB%84%E5%90%88%E5%A4%9A%E4%B8%AA-stores)是通过RootStore来实例化所有stores，并获取引用

**Comment by zhoujinfu** [comment]
Any updates to the issue? @LastLeaf

**Comment by zhoujinfu** [comment]
See https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/blob/master/src/behavior.ts#L33C16-L33C16

现版本已支持 `storeBindings` 为 Array
