### ISSUE TITLE
请问怎么搞，是我使用方式不对吗

### ISSUE THREAD

**Issue by acegank** [wechat-miniprogram/mobx-miniprogram-bindings#24]
不管是behaviors还是ComponentWithStore，ts都会报类型不对。。。

**Comment by TtTRz** [comment]
方便提供你的使用场景下的 demo 吗

**Comment by TtTRz** [comment]
> 不管是behaviors还是ComponentWithStore，ts都会报类型不对。。。

方便提供你的使用场景下的 demo 吗

**Comment by LastLeaf** [comment]
无活动，先关了。
