### ISSUE TITLE
可以在page和component中使用，那么如何在小程序的公用的js文件里面去取值和触发action

### ISSUE THREAD

**Issue by wangqi7916** [wechat-miniprogram/mobx-miniprogram-bindings#26]

**Comment by Wyatex** [comment]
取值：
```js
import {store}  from './store.js'
console.log(store.xxx)
```
触发action
```js
import { runInAction } from 'mobx-miniprogram'
import {store}  from './store.js'
function setData(arg) {
  runInAction(()=>{
    store.xx = arg
  })
}
```

**Comment by wangguohao** [comment]
> 取值：
> 
> ```js
> import {store}  from './store.js'
> console.log(store.xxx)
> ```
> 
> 触发action
> 
> ```js
> import { runInAction } from 'mobx-miniprogram'
> import { store }  from './store.js'
> export function setData(arg) {
>   runInAction(() => {
>     store.xx = arg
>   })
> }
> ```

我的项目用了 typescript，在非 Page 跟 Component 中引用 store 会导致编译报错

以下是引用方式，大佬能帮忙看下吗 

<img width="767" alt="image" src="https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/assets/8510286/1127f081-6805-4189-af65-940a53496063">

<img width="752" alt="image" src="https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/assets/8510286/22ef8179-6e4f-48eb-a843-9747ab90b2f1">

**Comment by Wyatex** [comment]
> 
> 我的项目用了 typescript，在非 Page 跟 Component 中引用 store 会导致编译报错
> 
> 以下是引用方式，大佬能帮忙看下吗
> 
> <img alt="image" width="767" src="https://private-user-images.githubusercontent.com/8510286/289227308-1127f081-6805-4189-af65-940a53496063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTA3NDgsIm5iZiI6MTcwMjA5MDQ0OCwicGF0aCI6Ii84NTEwMjg2LzI4OTIyNzMwOC0xMTI3ZjA4MS02ODA1LTQxODktYWY2NS05NDBhNTM0OTYwNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMDI1NDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzIyNTc5M2E5NzkzNjQ4ZjI5NTVkYzhmNmU1OGFhYTdjOTMwMjIzYzA4ZjcxM2M5NzkwYjA5NjcxYWNiYzM3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.otksqt-3EHOM7_uYriyieMFdJEFoTs-eMNk7VqSZg7Q"> <img alt="image" width="752" src="https://private-user-images.githubusercontent.com/8510286/289227401-22ef8179-6e4f-48eb-a843-9747ab90b2f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTA3NDgsIm5iZiI6MTcwMjA5MDQ0OCwicGF0aCI6Ii84NTEwMjg2LzI4OTIyNzQwMS0yMmVmODE3OS02ZTRmLTQ4ZWItYTg0My05NzQ3YWI5MGIyZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMDI1NDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmUzN2RjMzNlZmJjNmM2NDQwODA2YmNmMmM2YzUwMDdhMGYzZTlhMjc4ZmVlZGYwZTI3NGIwMTIxMjIzOGI1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5TNLnmbqpw2SU71S22zTYRmZgVEc72WIjy3wv7n6Z_o">

明显是你没有store.js那个文件啊，或者引用的路径不对，你看看我的demo：

https://github.com/Wyatex/mp-mobx-demo/blob/b7240a45e0d6c1cab49c02a478c043c419576153/src/store/test.ts#L1

https://github.com/Wyatex/mp-mobx-demo/blob/b7240a45e0d6c1cab49c02a478c043c419576153/src/components/component-a/component.ts#L3
