### ISSUE TITLE
异步action

### ISSUE THREAD

**Issue by 812781385** [wechat-miniprogram/mobx-miniprogram-bindings#28]
请问发送axios请求相应式改变store状态要怎么做？
 我现在store里的action里写了异步改变状态没有用

**Comment by Wyatex** [comment]
貌似异步的话只能用runInAction，[可以这样写](https://github.com/Wyatex/Weapp-Starter/blob/d48df3f784fd7ef3c3fef38e4c5509e1d935d11a/models/global.ts#L13)
