### ISSUE TITLE
是否支持按数据路径更新数据？

### ISSUE THREAD

**Issue by mrzhaichao** [wechat-miniprogram/mobx-miniprogram-bindings#29]
目前如果data 是 Array，需要全量设置Arrary，这样会导致根据Array渲染已渲染的的自定义组件会经过一次无意义的diff过程

**Comment by LastLeaf** [comment]
list-diff 算法 diff 的是节点树结构而不是数组本身。所以不管数组改了多少 diff 范围都是一样的。

不过全量设置 Array 确实会在其他方面有少量性能劣化。但这个和 MobX 配合的问题也不怎么好解决。
