### ISSUE TITLE
修改数据

### ISSUE THREAD

**Issue by happystudy666** [wechat-miniprogram/mobx-miniprogram-bindings#30]
如果我想在page中直接修改和component共享的数据不可以吗

**Comment by Wyatex** [comment]
按我的理解是用action或者runInAction修改store里的值，Page绑定的值就会响应式改变，如果是作为参数传入component的话component也能监听到变化。
所以说不应该直接修改Page中data的值，这样会导致其他Page没有拿到你修改的值。
