### ISSUE TITLE
文档里提到的ComponentWithStore和BehaviorWithStore是否可以考虑加入wechatminiprogram-typings的支持

### ISSUE THREAD

**Issue by dhlolo** [wechat-miniprogram/mobx-miniprogram-bindings#32]
![image](https://user-images.githubusercontent.com/50065494/220355363-6ede20da-9cf3-4723-8775-fc4f4a033155.png)

**Comment by LastLeaf** [comment]
这个应该不行了。

这个项目不能视为小程序的一部分。它的接口也是会跟着大版本变的。

只能说想想办法让类型能更容易注入进去。以后有 Chaining API 会好很多。
