### ISSUE TITLE
Ts:2.1.0以上版本会导致typeRoots报错

### ISSUE THREAD

**Issue by zhao-haoyang** [wechat-miniprogram/mobx-miniprogram-bindings#39]
![image](https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/assets/71298261/bbb2412e-0388-46c8-b647-be28a7bac64d)
好像是导致typeRoots失效了一样

**Comment by LastLeaf** [comment]
旧版本的本项目需要旧版本的 api-typings 才能共同工作。对于使用 TypeScript 的情况，建议升级到最新的本项目 + miniprogram-api-typings 。
