### ISSUE TITLE
typescript issue

### ISSUE THREAD

**Issue by shibaozhang95** [wechat-miniprogram/mobx-miniprogram-bindings#4]
你好，请问有打算支持 typescript 吗？
在使用 ts 开发小程序。引入包的时候报错
```
Could not find a declaration file for module 'mobx-miniprogram-bindings'
```

**Comment by JimYan** [comment]
在tyings/index.d.ts中新增：

declaration module 'mobx-miniprogram-bindings';

**Comment by xueyou2000** [comment]
> 在tyings/index.d.ts中新增：
> 
> declaration module 'mobx-miniprogram-bindings';

这样只是自己重新定义申明了, 无法用到包自带的types

**Comment by fanshuai** [comment]
期待官方支持

**Comment by missannil** [comment]
期待

**Comment by TtTRz** [comment]
已提供相关支持
