### ISSUE TITLE
请问如何正确的在app.js中使用Mobx？

### ISSUE THREAD

**Issue by shuimupj** [wechat-miniprogram/mobx-miniprogram-bindings#41]
参考Page的写法在app.js中使用，会报TypeError: r.setData is not a function；
同时app.js中没有onUnload如何调用destroyStoreBindings()？

**Comment by LastLeaf** [comment]
`storeBindings` 是将 MobX store 里的字段绑定到页面上。显然只适用于页面或者自定义组件。

在 app.js 里面用 MobX store 的话直接用 MobX 本身的接口就行了。
