### ISSUE TITLE
没有ts类型支持吗？

### ISSUE THREAD

**Issue by wyl086** [wechat-miniprogram/mobx-miniprogram-bindings#42]
如图所示，除非手动声明 `payTypes` 在 `data` 属性里，否则会报 `this.data` 上不存在 `paylypes` 。
![a64369245cb5b4ff73702ec5c9fddf4](https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/assets/57710268/6755a5cf-2b3d-45e3-ba61-ff52f6653c8f)

**Comment by LastLeaf** [comment]
这个是 Component() 接口本身的类型缺陷了。考虑用 `ComponentWithStore` ，或者自己手工写一下类型。
