### ISSUE TITLE
存在store里的字段太多是不是会影响页面的setData

### ISSUE THREAD

**Issue by neoprience** [wechat-miniprogram/mobx-miniprogram-bindings#43]
setDat一直提示超过长度，因为store放了很多
每次请求页面都会提示这个，而且越增越多
![image](https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/assets/46703103/db879d2a-aaaa-4e5c-8a72-af0e3cff9f24)

**Comment by LastLeaf** [comment]
store 里面放的东西很多的话，不要把它们全放到 storeBindings.fields 里面。 fields 里面被 setData 的。
