### ISSUE TITLE
每次修改store的时候都会触发setTimeout

### ISSUE THREAD

**Issue by neoprience** [wechat-miniprogram/mobx-miniprogram-bindings#44]
每次修改store的时候都会触发setTimeout, 这个定时器会清除吗，我发现一直再verbose里面警告，但是搜了bindings的源码没有settimeout，很无奈，我这个大程序性能不好的手机有点卡了

**Comment by neoprience** [comment]
![image](https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/assets/46703103/b9a97d70-b578-408f-9db2-3bcd0211c284)

**Comment by LastLeaf** [comment]
会的。

每次更新之后会等到 nextTick 再应用到界面上，要不然一下子改很多次 data 的话性能太差了。
