### ISSUE TITLE
请问一下，behavior 绑定模式下，使用的Component 构造器来创建的页面，在页面卸载的时候怎么重置数据

### ISSUE THREAD

**Issue by gaoyouAwait** [wechat-miniprogram/mobx-miniprogram-bindings#45]
原以为behavior 绑定会在页面跳转之后自动销毁的，使用之后发现数据没有重置，page模式下是可以调用destroyStoreBindings方法销毁数据的
![Snipaste_2024-04-03_17-34-47](https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/assets/34308245/95d09644-49bb-49d7-b84a-9c3b2d96943a)

**Comment by LastLeaf** [comment]
注意 store 本身不会随着 storeBindings 销毁。
