### ISSUE TITLE
actions 字段未进入 TMethod

### ISSUE THREAD

**Issue by liaokaime** [wechat-miniprogram/mobx-miniprogram-bindings#47]
ComponentWithStore > storeBindings > actions声明了字段，写在 onShow中写 this 时没有任何提示，然会报红

**Comment by posrix** [comment]
这个问题如何解决？目前只能ts-ignore

**Comment by LastLeaf** [comment]
看起来现在的接口没法做出来想要的效果。可能要搞一个更加类型友好的接口。
