### ISSUE TITLE
还可以用么？

### ISSUE THREAD

**Issue by callmesoul** [wechat-miniprogram/mobx-miniprogram-bindings#5]
还可以用么？怎么看微信的的本档把mobx-miniprogram 移除了？

**Comment by LastLeaf** [comment]
没问题的。文档上留了 mobx-miniprogram-bindings : https://developers.weixin.qq.com/miniprogram/dev/extended/utils/mobx.html 。

当然你也可以只用 mobx-miniprogram （因为基本上就是 mobx ，文档就没有单独写了）。
