### ISSUE TITLE
Component this.data.xxx，xxx未声明的情况下推导为any

### ISSUE THREAD

**Issue by lv-z-l** [wechat-miniprogram/mobx-miniprogram-bindings#52]
case:
![image](https://github.com/user-attachments/assets/a50c7d2c-e15f-49e9-aeea-462f2c2d0093)
![image](https://github.com/user-attachments/assets/285c1aa7-ca14-4f7d-bcf5-226d73e1c4b4)

fix:
![image](https://github.com/user-attachments/assets/1c89bf16-672e-416a-8338-739d9fe5fc6d)

**Comment by LastLeaf** [comment]
是不是提错地方了？看起来是 [api-typings](https://github.com/wechat-miniprogram/api-typings) 那边的？

**Comment by lv-z-l** [comment]
不好意思哈，确实提错了
