### ISSUE TITLE
在Page错误使用 behaviors, storeBindings的方法进行绑定后，该store的属性设置失效。

### ISSUE THREAD

**Issue by chenkigba** [wechat-miniprogram/mobx-miniprogram-bindings#54]
页面1，onLoad createStoreBindings创建绑定，可以正常通过登录组件设置登录状态。this.isLoggedIn = true，打印出来也为true。
页面2，Page，通过 storeBidings 创建绑定。一旦打开页面2后，即使回到页面1，也无法正确设置store的状态。

真是个奇怪的现象....

**Comment by chenkigba** [comment]
顺便问下， this.storeBindings 如果传入一个 createStoreBidings的 数组，也只有最后一个绑定的数据可以通过 this.data.xxxx 的方式获取.... 其他都得用 toJS(xxxStore.xxx)获取。这是为什么我后面在page上用了storeBindings的原因，因为没看到官方示例怎么用createStoreBindings创建多个数据绑定。（最后Page+storeBindings导致更迷惑的bug，找了一个小时原因》。。

**Comment by chenkigba** [comment]
![image](https://github.com/user-attachments/assets/e426623c-5bbd-4292-95f9-d3a48232599f)
![image](https://github.com/user-attachments/assets/65378f4f-48ee-496c-a63c-4731565ea264)
让我以为page能用storeBindings进行绑定的是图一，但是图二又说适用于component

**Comment by LastLeaf** [comment]
behavior 绑定也适用于 Page 构造器，但是需要小程序的基础库版本支持在 Page 构造器中使用 behavior （>=2.9.2）。目前最新版本的本模块需要 >=2.11.0 ，已经高于此要求，是没问题的；如果使用老版本的本模块需要注意一下。

**Comment by LastLeaf** [comment]
对于主贴的问题：我没有完全看明白是个什么问题。麻烦再详细点说明下。

**Comment by chenkigba** [comment]
> 对于主贴的问题：我没有完全看明白是个什么问题。麻烦再详细点说明下。

前两天在修bug，我详细说明一下：
页面A：behaviour 绑定 3 个 MobX 数据，其中有一个是 userStore。
页面B：createStoreBindings 绑定 userStore。

当用户未设置 userStore 的 userInfo 时，弹出 welcome 组件，点击登录按钮登录，登录成功后会设置 MobX 的 userStore 的 userInfo。
此时预期的表现是 我在 action 函数 setUserInfo(userInfo) 中使用 this.userInfo = userInfo，将welcome传入的用户信息进行设置。然后打印 this.userInfo，应当打印传入的 userInfo。（这里的this不是bindings里面的this，我知道这个是nextTick更新，而是MobX的userStore的this，即赋值下一行打印。）

**但是，如果我进入了页面A，也就是通过 behaviour 绑定 userStore 的页面，则welcome调用userStore/setUserInfo 打印 this.userInfo 是 undefined，直接打印传入的参数 userInfo 正常。** 进入页面 B，登录功能正常，打印内容正常。

**更让人迷惑的是，如果我进入了页面A，再进入页面B，然后调用页面B的登录，此时也无法正确设置  this.userInfo。**

希望以上内容对你理解有帮助，因为还在搞开发工作没法给你写一个最小复现单元出来。

**Comment by LastLeaf** [comment]
> > 对于主贴的问题：我没有完全看明白是个什么问题。麻烦再详细点说明下。
> 
> 前两天在修bug，我详细说明一下： 页面A：behaviour 绑定 3 个 MobX 数据，其中有一个是 userStore。 页面B：createStoreBindings 绑定 userStore。
> 
> 当用户未设置 userStore 的 userInfo 时，弹出 welcome 组件，点击登录按钮登录，登录成功后会设置 MobX 的 userStore 的 userInfo。 此时预期的表现是 我在 action 函数 setUserInfo(userInfo) 中使用 this.userInfo = userInfo，将welcome传入的用户信息进行设置。然后打印 this.userInfo，应当打印传入的 userInfo。（这里的this不是bindings里面的this，我知道这个是nextTick更新，而是MobX的userStore的this，即赋值下一行打印。）
> 
> **但是，如果我进入了页面A，也就是通过 behaviour 绑定 userStore 的页面，则welcome调用userStore/setUserInfo 打印 this.userInfo 是 undefined，直接打印传入的参数 userInfo 正常。** 进入页面 B，登录功能正常，打印内容正常。
> 
> **更让人迷惑的是，如果我进入了页面A，再进入页面B，然后调用页面B的登录，此时也无法正确设置 this.userInfo。**
> 
> 希望以上内容对你理解有帮助，因为还在搞开发工作没法给你写一个最小复现单元出来。

看你的意思是 store.userInfo 没有正常被设置？

这个模块是将 mobx 用于 page/component 的绑定模块，是不会影响 store 本身的数据和 action 的。如果 store 本身数据不正常，应该不是受到这个模块本身逻辑的影响。

我觉得最有可能的原因是，这个 store 是不是能确定是一个全局单例？如果不是的话，我猜测最有可能的原因是不同的页面访问了不同的 store 实例导致的，建议先朝这个方向查一下。

有什么疑问的话，可以再详细点说明。
