### ISSUE TITLE
typescript中使用ComponentWithComputed,ComponentWithStore构建组件无法添加behaviors

### ISSUE THREAD

**Issue by lilin87788** [wechat-miniprogram/mobx-miniprogram-bindings#55]
1、ComponentWithComputed爆红
![image](https://github.com/user-attachments/assets/7e6d7952-028b-451d-a532-97c86f716fa8)

2、ComponentWithStore爆红
![image](https://github.com/user-attachments/assets/718ed82b-9392-4fc1-8913-383c1d16ba67)

3、Component正常
![image](https://github.com/user-attachments/assets/d56575b7-b15d-4716-b9ca-b004e70dcd35)

**Comment by LastLeaf** [comment]
用的版本号是？

**Comment by lilin87788** [comment]
5.1.0 我确认了 全部都是最新的，我感觉还是有好多问题 ，比如这个 微信官方要求这个WechatMiniprogram.Component.Instance 类型的第四个泛型必须继承BehaviorOption 
![image](https://github.com/user-attachments/assets/ca132816-67ee-4ae6-8a20-3ede10f2abcb)
另外 ComponentWithStore，ComponentWithComputed 等方法 我如果只想设置TData 这个别的用缺省的 好像不太方便

**Comment by lilin87788** [comment]
![image](https://github.com/user-attachments/assets/908bd6d5-7dc9-45d4-9d46-d29e279e951e)
这是版本号信息

**Comment by lilin87788** [comment]
![image](https://github.com/user-attachments/assets/c5a24c86-94b1-4948-8ef4-10692c3f65b2)
爆红的问题 我这么修改声明文件就正常了

**Comment by lilin87788** [comment]
> 5.1.0 我确认了 全部都是最新的，我感觉还是有好多问题 ，比如这个 微信官方要求这个WechatMiniprogram.Component.Instance 类型的第四个泛型必须继承BehaviorOption ![image](https://private-user-images.githubusercontent.com/1483811/377725405-ca132816-67ee-4ae6-8a20-3ede10f2abcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjc1MjcsIm5iZiI6MTcyOTIyNzIyNywicGF0aCI6Ii8xNDgzODExLzM3NzcyNTQwNS1jYTEzMjgxNi02N2VlLTRhZTYtOGEyMC0zZWRlMTBmMmFiY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDQ1MzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdhNDU5OTgxYTljN2MxOGQ3Nzg2NzAxMWEyNzEzNjY4NDhmZjVlNTkwZjAwN2ExMzYwYjMyODc3Y2VlOTc1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.W874bG3boSkwtxnpyDKcoslHk2y5WHti9ZYWC6nIAf8) 另外 ComponentWithStore，ComponentWithComputed 等方法 我如果只想设置TData 这个别的用缺省的 好像不太方便

我想要的使用方式这样
ComponentWithComputed<IComponentData>,但是现在不行，要么不设置，要么必须一次设置4个泛型，
![image](https://github.com/user-attachments/assets/db24f916-1bc0-43ef-9d4d-5f7b629d4d29)

**Comment by LastLeaf** [comment]
> 5.1.0 我确认了 全部都是最新的，我感觉还是有好多问题 ，比如这个 微信官方要求这个WechatMiniprogram.Component.Instance 类型的第四个泛型必须继承BehaviorOption ![image](https://private-user-images.githubusercontent.com/1483811/377725405-ca132816-67ee-4ae6-8a20-3ede10f2abcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzQ0NzUsIm5iZiI6MTcyOTIzNDE3NSwicGF0aCI6Ii8xNDgzODExLzM3NzcyNTQwNS1jYTEzMjgxNi02N2VlLTRhZTYtOGEyMC0zZWRlMTBmMmFiY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDY0OTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAxMmQ4ZDcwNmJhMWMxODI1NTY4MGZjMDQwZTRhNzc4ODdjMDFjNTI2MDJhMDUwNTE1MDRmOTMzZTBkOWVhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zTuB3GOmXdqELDE95Byss50z5LV_Tqu5jBYINojABlU) 另外 ComponentWithStore，ComponentWithComputed 等方法 我如果只想设置TData 这个别的用缺省的 好像不太方便

TypeScript 本身限制要写泛型就得写全，这没办法

**Comment by lilin87788** [comment]
> 要写泛型就得写全，这没

我看你的 最后面那个泛型参数 就设置了默认值

**Comment by LastLeaf** [comment]
> 5.1.0 我确认了 全部都是最新的，我感觉还是有好多问题 ，比如这个 微信官方要求这个WechatMiniprogram.Component.Instance 类型的第四个泛型必须继承BehaviorOption ![image](https://private-user-images.githubusercontent.com/1483811/377725405-ca132816-67ee-4ae6-8a20-3ede10f2abcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzQ0NzUsIm5iZiI6MTcyOTIzNDE3NSwicGF0aCI6Ii8xNDgzODExLzM3NzcyNTQwNS1jYTEzMjgxNi02N2VlLTRhZTYtOGEyMC0zZWRlMTBmMmFiY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDY0OTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAxMmQ4ZDcwNmJhMWMxODI1NTY4MGZjMDQwZTRhNzc4ODdjMDFjNTI2MDJhMDUwNTE1MDRmOTMzZTBkOWVhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zTuB3GOmXdqELDE95Byss50z5LV_Tqu5jBYINojABlU) 另外 ComponentWithStore，ComponentWithComputed 等方法 我如果只想设置TData 这个别的用缺省的 好像不太方便

这里第一行应该是有个 `Partial<WechatMiniprogram.Component.OtherOption>` 的？这个 `OtherOption` 里面应该有 `behaviors` 字段，不需要自己补一个才对。

**Comment by LastLeaf** [comment]
> ![image](https://private-user-images.githubusercontent.com/1483811/377726468-c5a24c86-94b1-4948-8ef4-10692c3f65b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzQ0NzUsIm5iZiI6MTcyOTIzNDE3NSwicGF0aCI6Ii8xNDgzODExLzM3NzcyNjQ2OC1jNWEyNGM4Ni05NGIxLTQ5NDgtOGVmNC0xMDY5MmMzZjY1YjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDY0OTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ5MTIxMTYyZDQwNmJiYzk5YjU2MjUwY2Y5YTllNWY3ZmE3ZDY5NzkyNTdjOGQ0MWFiNmM3MDAyYzQ1YjBiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F4bNHVyCQD86hVcuzbHdsRbFUHKWnNyDLr547ivMAXc) 爆红的问题 我这么修改声明文件就正常了

这里第一行应该是有个 Partial<WechatMiniprogram.Component.OtherOption> 的？这个 OtherOption 里面应该有 behaviors 字段，不需要自己补一个才对。

**Comment by LastLeaf** [comment]
> > 要写泛型就得写全，这没
> 
> 我看你的 最后面那个泛型参数 就设置了默认值

只有末尾的才能默认值，这全写上默认值感觉也不太好。这里本来也不鼓励直接写类型参数值。

想显式指定 data 的类型，在 `data: {}` 那里用个 `as DESIRED_TYPE` 就好了。

**Comment by lilin87788** [comment]
麻烦还帮我看下Behavior 爆红的问题 

> > ![image](https://private-user-images.githubusercontent.com/1483811/377726468-c5a24c86-94b1-4948-8ef4-10692c3f65b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzQ0NzUsIm5iZiI6MTcyOTIzNDE3NSwicGF0aCI6Ii8xNDgzODExLzM3NzcyNjQ2OC1jNWEyNGM4Ni05NGIxLTQ5NDgtOGVmNC0xMDY5MmMzZjY1YjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDY0OTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ5MTIxMTYyZDQwNmJiYzk5YjU2MjUwY2Y5YTllNWY3ZmE3ZDY5NzkyNTdjOGQ0MWFiNmM3MDAyYzQ1YjBiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F4bNHVyCQD86hVcuzbHdsRbFUHKWnNyDLr547ivMAXc) 爆红的问题 我这么修改声明文件就正常了
> 
> 这里第一行应该是有个 Partial<WechatMiniprogram.Component.OtherOption> 的？这个 OtherOption 里面应该有 behaviors 字段，不需要自己补一个才对。

麻烦确认下 我看没有这个字段

**Comment by LastLeaf** [comment]
> 麻烦还帮我看下Behavior 爆红的问题
> 
> > > ![image](https://private-user-images.githubusercontent.com/1483811/377726468-c5a24c86-94b1-4948-8ef4-10692c3f65b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzQ0NzUsIm5iZiI6MTcyOTIzNDE3NSwicGF0aCI6Ii8xNDgzODExLzM3NzcyNjQ2OC1jNWEyNGM4Ni05NGIxLTQ5NDgtOGVmNC0xMDY5MmMzZjY1YjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDY0OTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ5MTIxMTYyZDQwNmJiYzk5YjU2MjUwY2Y5YTllNWY3ZmE3ZDY5NzkyNTdjOGQ0MWFiNmM3MDAyYzQ1YjBiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F4bNHVyCQD86hVcuzbHdsRbFUHKWnNyDLr547ivMAXc) 爆红的问题 我这么修改声明文件就正常了
> > 
> > 
> > 这里第一行应该是有个 Partial<WechatMiniprogram.Component.OtherOption> 的？这个 OtherOption 里面应该有 behaviors 字段，不需要自己补一个才对。
> 
> 麻烦确认下 我看没有这个字段

behaviors 字段是来自于 WechatMiniprogram.Component.OtherOption 的

**Comment by lilin87788** [comment]
> > 麻烦还帮我看下Behavior 爆红的问题
> > > > ![image](https://private-user-images.githubusercontent.com/1483811/377726468-c5a24c86-94b1-4948-8ef4-10692c3f65b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzQ0NzUsIm5iZiI6MTcyOTIzNDE3NSwicGF0aCI6Ii8xNDgzODExLzM3NzcyNjQ2OC1jNWEyNGM4Ni05NGIxLTQ5NDgtOGVmNC0xMDY5MmMzZjY1YjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDY0OTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ5MTIxMTYyZDQwNmJiYzk5YjU2MjUwY2Y5YTllNWY3ZmE3ZDY5NzkyNTdjOGQ0MWFiNmM3MDAyYzQ1YjBiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F4bNHVyCQD86hVcuzbHdsRbFUHKWnNyDLr547ivMAXc) 爆红的问题 我这么修改声明文件就正常了
> > > 
> > > 
> > > 这里第一行应该是有个 Partial<WechatMiniprogram.Component.OtherOption> 的？这个 OtherOption 里面应该有 behaviors 字段，不需要自己补一个才对。
> > 
> > 
> > 麻烦确认下 我看没有这个字段
> 
> behaviors 字段是来自于 WechatMiniprogram.Component.OtherOption 的
我仔细看了至少WechatMiniprogram.Component.OtherOption  这个Interface 里面没有
![image](https://github.com/user-attachments/assets/ed04c74c-be9d-487d-8148-b1de48d4dd70)
![image](https://github.com/user-attachments/assets/a841e869-f325-4312-a034-3ae9b45480d9)

**Comment by lilin87788** [comment]
我能发一个有问题的代码给你吗

**Comment by LastLeaf** [comment]
> 我能发一个有问题的代码给你吗

公开具体代码的话，麻烦确认代码已经业务脱敏，并且是尽量小的能复现问题的代码片段。

**Comment by gaoxiu333** [comment]
我也有同样的问题，使用 ComponentWithStore 构造器时，behaviors 会有类型提示错误

**Comment by LastLeaf** [comment]
> 我也有同样的问题，使用 ComponentWithStore 构造器时，behaviors 会有类型提示错误

@gaoxiu333 看看是不是和上面 OtherOption 的截图一样（缺少 behaviors 字段）？

**Comment by gaoxiu333** [comment]
> > 我也有同样的问题，使用 ComponentWithStore 构造器时，behaviors 会有类型提示错误
> 
> @gaoxiu333 看看是不是和上面 OtherOption 的截图一样（缺少 behaviors 字段）？

是这样我这里也是最新的`miniprogram-api-typings@4.0.1`，如下图：
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/23db849c-1cd4-47f9-ab73-3cdc805ddea0">

**Comment by LastLeaf** [comment]
目前和 miniprogram-api-typings v4 不兼容， package.json 里面现在是 v3 的。

**Comment by LastLeaf** [comment]
已在 v5.0.0 中修复。需要使用 miniprogram-api-typings ^4.0.0 。

**Comment by lilin87788** [comment]
还是没有Behavior字段 麻烦作者帮我解决下
