### ISSUE TITLE
TS使用ComponentWithStore时，当存在多个storeBindings元素时，无法在this上找到action方法

### ISSUE THREAD

**Issue by xieweixin** [wechat-miniprogram/mobx-miniprogram-bindings#56]
ComponentWithStore({
  storeBindings: [
    {
       namespace: "xxx",
       store: store1,
       fields: {}  as const,
       actions: {
         a1: "a1"
       } as const
    },
    {
       namespace: "yyy",
       store: store2,
       fields: {}  as const,
       actions: {
        
       } as const
    }
  ]
})
调用 this.a1时，爆红，storeBindings里只有一个时不存在问题，版本是4.0.1

**Comment by LastLeaf** [comment]
已知问题。不怎么好解决。
