### ISSUE TITLE
observable 的对象，直接修改内部属性后不会触发渲染

### ISSUE THREAD

**Issue by MeloGuo** [wechat-miniprogram/mobx-miniprogram-bindings#9]
例如有这样一个 store
```javascript
class PersonStore {
  @observable obj = {
    key1: 'a',
    key2: 'b'
  }
  
  @action
  setKey1(str) {
    this.obj.key1 = str
  }

  @action
  setKey2(str) {
    this.obj = { key1: this.obj.key1, key2: str }
  }
}
```
将它实例化后将 obj 渲染到页面中:
```html
<view bind:tap="onTapKey1">key1 is: {{obj.key1}}</view>
<view bind:tap="onTapKey2">key2 is: {{obj.key2}}</view>
```
```javascript
Page({
  // 省略绑定的代码
  onTapKey1() {
    this.setKey1('c') // 视图不会被更新
  },
  onTapKey2() {
    this.setKey2('d') // 视图会被更新
  }
})
```
所以直接修改对象中的属性不会让视图更新，但是在 React 中使用 mobx-react 是支持这种方式更新视图的。
**所以这是 Bug 还是就这么设计的 Feature 呢？**

**Comment by MeloGuo** [comment]
看了下源码，搞清楚了，如果希望直接修改 key1 就被渲染应该这么写：
```javascript
Page({
  onLoad() {
    this.storeBindings = createStoreBindings(this, {
      store,
      fields: {
        'obj.key1': store => store.obj.key1,
        'obj.key2': store => store.obj.key2,
      },
      actions: ['setKey1', 'setKey2'],
    })
  }
})
```
因为其实 setData 的操作是在 reaction 中根据传入 store 字段的粒度来决定的。
![image](https://user-images.githubusercontent.com/22138516/77313465-e5dbab00-6d3e-11ea-8ddb-649b57db29c9.png)
希望在文档里写一下这点吧，不然容易误会。

**Comment by LastLeaf** [comment]
这个问题之前在另一个地方讨论过。

我是打算给启用 `reaction` 的配置项 `equals: comparer.structural` 这样来解决这个问题的。你觉得如何？

**Comment by MeloGuo** [comment]
> 这个问题之前在另一个地方讨论过。
> 
> 我是打算给启用 `reaction` 的配置项 `equals: comparer.structural` 这样来解决这个问题的。你觉得如何？

我比较困惑这个配置的作用，因为我看 comparer.structural 是对新数据和旧数据进行了一次 deepEqual,
返回一个布尔值，所以我就在这里写死一个函数，始终返回 false。
```javascript
reactions = fields.map((field) => {
  return reaction(() => store[field], (value) => {
    scheduleSetData(field, value)
  }, {
      fireImmediately: true,
      equals: () => false
    })
})
```
但是这时如果执行上面第一段代码的操作 
`@action
  setKey1(str) {
    this.obj.key1 = str
  }`依然是无效的，根本不会触发 equals 这个回调函数。

**Comment by LastLeaf** [comment]
OK... 这个例子确实也是不行。

仔细看了一下， mobx 对这种情况好像是没有支持的。那只有在文档上说明一下了。

**Comment by MeloGuo** [comment]
我尝试去把对象里的属性给每个都加上 reaction 也不太行。
```javascript
function deepReaction(store, fields, path = []) {
  return fields.map(field => {
    const value = store[field]
    if (typeof value === 'object' && value) {
      return deepReaction.call(this, value, Object.keys(value), [...path, field])
    } else {
      const key = `${path.join('.')}.${field}`
      return reaction(() => value, value => {
        scheduleSetData(key, value)
      }, {
        fireImmediately: true
      })
    }
  })
}

// 拍平数组
function flatArray(array) {
  return array.reduce((result, value) => {
    if (Array.isArray(value)) {
      result.push(...flatArray(value))
    } else {
      result.push(value)
    }
    return result
  }, [])
}

// 传入的 fields 为 array 的情况
reactions = flatArray(deepReaction.call(store, store, fields))
```
这里的问题是在 reaction 的第一个函数中，如果直接返回一个非 obserable 的值是不行的：`reaction(() => value)`。
而必需得是从 observeabl 的值上引用的这种形式 `reaction(() => store[key])`，但是 JavaScript 不支持 key 这个字符串访问深层属性的情况，不知道还能不能想到什么好办法？

**Comment by LastLeaf** [comment]
这里的核心问题还是，只改变 observable 字段的子字段不会触发 observable 。你这样做也太暴力了……

应该是没什么办法了。

**Comment by MeloGuo** [comment]
> 这里的核心问题还是，只改变 observable 字段的子字段不会触发 observable 。你这样做也太暴力了……
> 
> 应该是没什么办法了。

😂确实暴力，那好吧，感谢回复。

**Comment by LastLeaf** [comment]
更新了文档。
